### ISSUE TITLE
Rmagick does not seem to be compatible with Imagemagick 7

### ISSUE THREAD

**Issue by 6temes** [rmagick/rmagick#265] opened 2017-02-14 04:14 UTC
I think that it would be really helpful to explain in the Readme that Rmagick will not work with the default version of Imagemagick

Install instructions for MacOS:

http://stackoverflow.com/a/41747901/2995613

**Comment by DoubleDroz** [comment] 2017-02-16 06:11
It would be nice if, after installing imagemagick@6 with brew, we could simply point rmagick at the @6 version, but still keep the latest and greatest?

Unless of course there is such a way...

**Comment by alex-mayr** [comment] 2017-02-16 13:24
what about adjusting the gem so it works for the latest version? guess I'm not the only one who doesn't want to have outdated software on their servers

**Comment by linduxed** [comment] 2017-02-16 16:47
@alex-mayr Apparently it's non-trivial to achieve compatibility with version 7. See #256 for more discussion.

**Comment by alex-mayr** [comment] 2017-02-17 10:39
@linduxed ok, that's nasty. thank you

**Comment by jullit31** [comment] 2017-08-13 16:20
At least someone should, as suggested originally, update the readme not to say

> ImageMagick Version 6.4.9 or later.

**Comment by seliverstov-maxim** [comment] 2017-12-04 08:58
Yep, I create a PullRequest https://github.com/rmagick/rmagick/pull/284

**Comment by kimpepper** [comment] 2018-05-30 00:38
I added #299 to kick start the porting process.

**Comment by mockdeep** [comment] 2019-03-09 16:59
duplicate of #256

**Closed by mockdeep** 2019-03-09 16:59 UTC
Labels: ImageMagick 7
