### ISSUE TITLE
how to build rmagick 2.13.4 on windows x64 with x64_mingw32 and imagemagick 6.9.0-8-Q16-x64

### ISSUE THREAD

**Issue by abaumgaertner** [rmagick/rmagick#175] opened 2015-03-01 12:08 UTC
it is possible ... here is how it's done ...
this works with ruby 2.1.5 and ruby 2.2.1
1. get the imagemagick binaries
   ftp://ftp.sunet.se/pub/multimedia/graphics/ImageMagick/binaries/
   e.g. ImageMagick-6.9.0-8-Q16-x64-dll.exe
   (get the DLL version and the Q8 or Q16 depth you need)
2. install imagemagick - don't forget to tick the headers
3. the included lib files are not compatible with ld so you have to regenerate them using gendef and dlltool
   - gendef CORE_RL_magick_.dll
   - dlltool --dllname CORE_RL_magick_.dll --def CORE_RL_magick_.def --output-lib 
     CORE_RL_magick_.lib
   - repeat this for CORE_RL_Magick++_.dll, CORE_RL_wand_.dll
   - make sure you overwrite the files in the lib directory
4. clone the gem from github
   - git clone https://github.com/gemhome/rmagick.git
   - this is important - the extconf.rb has improved since the release of 2.13.4
5. build the gem
   - gem build rmagick.gemspec
6. install the gem (devkit must be installed)
   - gem install rmagick --platform=ruby --local c:/somepath/rmagick-2.13.4.gem -- "--with-opt-dir=c:/someotherpath/ImageMagick" "--with-opt-lib=c:/someotherpath/ImageMagick/lib" "--with-opt-include=c:/someotherpath/ImageMagick/include"

Now you can use rmagick ...

the issue within the current release is in extconf.rb - it references the x11.lib which is really out of date and broke all my efforts to get rmagick running.

The best solution to this would be to include the binaries (imagemagick dlls) in the gem / platform ...

tested with
ruby 2.2.1p85 (2015-02-26 revision 49761) [x64-mingw32]
ruby 2.1.5p299 (2015-02-19 revision 49652) [x64-mingw32]

**Comment by vassilevsky** [comment] 2015-03-01 16:25
WOW. This is some serious knowledge. Thanks for sharing!

Can you edit `exconf.rb` to remove the bad reference and make the gem buildable on Windows out of the box? We'll be happy to help you with any necessary changes in Ruby.

`rake-compiler` (we use it to build the gem for tests) can build precompiled gems for Windows:

https://github.com/rake-compiler/rake-compiler

Can we do that?

We can also set up compilation on Windows on http://www.appveyor.com if that's the only way.

Please let us know how to make this.

**Comment by ABaumgaertner** [comment] 2015-03-02 09:36
thanks for continuing the imagemagick integration ...

the problem with appveyor is that the site depends on rubyinstaller binaries which are not available for ruby 2.2 yet but starting with ruby 2.0 and 2.1 would probably help a lot of people already

ruby 2.2 has not launched properly on windows yet - there were issues with the ffi (dl was deprecated) interface - solved
brianmario/mysql2#584

there is still an issue open with gem handling and multiple platform binaries - open
rubygems/rubygems#1179

I'm not a ruby developer and not expierenced with rubygems.org but when I look at mysql2 repo it seems fairly easy to generate and include the binaries using rake compiler.

The only obstacle I see is generating the definition files for the imagemagick dlls. I can help you out with these ...

**Comment by u338steven** [comment] 2015-03-02 13:02
Thanks for sharing!

There are 2 things that concern me.
I'd like to get more infomation about them. (e.g. build error messages)

 --- 

> \3. the included lib files are not compatible with ld 

On my box (Windows 7 SP1), the lib files are compatible with ```ld``` so I can build rmagick with them just as they are.

my ```ld``` version: 
```sh
C:\>ld -v
GNU ld (rubenvb-4.7.2-release) 2.23.51.20120920
```

ImageMagick:
ftp://ftp.imagemagick.org/pub/ImageMagick/binaries/ImageMagick-6.9.0-9-Q16-x64-dll.exe
```
C:\>convert --version
Version: ImageMagick 6.9.0-9 Q16 x64 2015-02-28 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: DPC Modules OpenMP
Delegates (built-in): bzlib cairo freetype jbig jng jp2 jpeg lcms lqr openexr pangocairo png ps rsvg tiff webp xml zlib
```

 --- 

> the issue within the current release is in extconf.rb - it references the x11.lib which is really out of date and broke all my efforts to get rmagick running.

Hmm... the current release(rmagick 2.13.4) should not reference ```x11.lib``` on x64-mingw32.

```rb
  if RUBY_PLATFORM =~ /x64/
    $LOCAL_LIBS = '-lCORE_RL_magick_'
```

<cite>[rmagick/extconf.rb at RMagick_2-13-4 · gemhome/rmagick](https://github.com/gemhome/rmagick/blob/RMagick_2-13-4/ext/RMagick/extconf.rb#L190)</cite>

**Comment by ABaumgaertner** [comment] 2015-03-02 15:46
here is my devkit env
```
$ ld -v
GNU ld (GNU Binutils) 2.25

$ gcc -v
Using built-in specs.
COLLECT_GCC=D:\msys64\mingw64\bin\gcc.exe
COLLECT_LTO_WRAPPER=D:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/4.9.2/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: ../gcc-4.9.2/configure --prefix=/mingw64 --with-local-prefix=/mingw64/local --build=x86_64-w64-mingw32 --host=x86_64-w64-mingw32 --target=x86_64-w64-mingw32 --with-native-system-header-dir=/mingw64/x86_64-w64-mingw32/include --libexecdir=/mingw64/lib --with-gxx-include-dir=/mingw64/include/c++/4.9.2 --enable-bootstrap --with-arch=x86-64 --with-tune=generic --enable-languages=c,lto,c++,objc,obj-c++,fortran,ada --enable-shared --enable-static --enable-libatomic --enable-threads=posix --enable-graphite --enable-fully-dynamic-string --enable-libstdcxx-time=yes --disable-libstdcxx-pch --disable-libstdcxx-debug --enable-cloog-backend=isl --enable-version-specific-runtime-libs --disable-cloog-version-check --disable-isl-version-check --enable-lto --enable-libgomp --disable-multilib --enable-checking=release --disable-rpath --disable-win32-registry --disable-nls --disable-werror --disable-symvers --with-libiconv --with-system-zlib --with-gmp=/mingw64 --with-mpfr=/mingw64 --with-mpc=/mingw64 --with-isl=/mingw64 --with-cloog=/mingw64 --with-pkgversion='Rev4, Built by MSYS2 project' --with-bugurl=http://sourceforge.net/projects/msys2 --with-gnu-as --with-gnu-ld
Thread model: posix
gcc version 4.9.2 (Rev4, Built by MSYS2 project)

convert.exe -v
Version: ImageMagick 6.9.0-8 Q16 x64 2015-02-21 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: DPC Modules OpenMP
Delegates (built-in): bzlib cairo freetype jbig jng jp2 jpeg lcms lqr openexr pangocairo png ps rsvg tiff webp xml zlib
```
x11 is still referenced for x32 and mswin - and it's not included in the x86 imagemagick binaries anymore. from the unpacked gem rmagick-2.13.4.gem
```ruby
elsif RUBY_PLATFORM =~ /mingw/  # mingw

  `convert -version` =~ /Version: ImageMagick (\d+\.\d+\.\d+)-\d+ /
  abort "Unable to get ImageMagick version" unless $1
  $magick_version = $1
  if RUBY_PLATFORM =~ /x64/
    $LOCAL_LIBS = '-lCORE_RL_magick_'
  else
    $LOCAL_LIBS = '-lCORE_RL_magick_ -lX11'
  end

else  # mswin

  `convert -version` =~ /Version: ImageMagick (\d+\.\d+\.\d+)-\d+ /
  abort "Unable to get ImageMagick version" unless $1
  $magick_version = $1
  $CFLAGS = "-W3"
  $CPPFLAGS = %Q{-I"C:\\Program Files\\Microsoft Platform SDK for Windows Server 2003 R2\\Include" -I"C:\\Program Files\\ImageMagick-#{$magick_version}-Q8\\include"}
  # The /link option is required by the Makefile but causes warnings in the mkmf.log file.
  $LDFLAGS = %Q{/link /LIBPATH:"C:\\Program Files\\Microsoft Platform SDK for Windows Server 2003 R2\\Lib" /LIBPATH:"C:\\Program Files\\ImageMagick-#{$magick_version}-Q8\\lib" /LIBPATH:"C:\\ruby\\lib"}
  $LOCAL_LIBS = 'CORE_RL_magick_.lib X11.lib'

end
```
I see one issue on my side - gcc was preinstalled for this env and not recompiled by me - so threadmodel is posix not win32. That probably caused the incompatibility of the lib files. I'll get back to you on this one.

**Comment by u338steven** [comment] 2015-03-03 10:56
Oh, I understand this issue occurs not only on x64-mingw32.
I saw the title of the issue and thought this occurs only on x64-mingw32...

> it's not included in the x86 imagemagick binaries anymore. 

Thanks for the information!
I didn't know that.

It might be ImageMagick ver.6.9.0-X that ```X11.lib``` was removed in.
(I confirmed 6.9.0-0 include ```X11.lib```, but 6.9.0-9 does not)

We should fix it for x86-mingw32 and mswin.

 --- 

> threadmodel is posix not win32. That probably caused the incompatibility of the lib files.

It could be so.

my ```gcc```:

```
C:\>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=c:/ruby/devkit/mingw/bin/../libexec/gcc/x86_64-w64-mingw32/4.7.2/lto-wrapper.exe
Target: x86_64-w64-mingw32
Configured with: /home/ruben/mingw-w64/src/gcc/configure --host=x86_64-w64-mingw32 --build=x86_64-linux-gnu --target=x86_64-w64-mingw32 --with-sysroot=/home/ruben/mingw-w64/mingw64mingw64/mingw64 --prefix=/home/ruben/mingw-w64/mingw64mingw64/mingw64 --with-gmp=/home/ruben/mingw-w64/prereq/x86_64-w64-mingw32/install --with-mpfr=/home/ruben/mingw-w64/prereq/x86_64-w64-mingw32/install --with-mpc=/home/ruben/mingw-w64/prereq/x86_64-w64-mingw32/install --with-ppl=/home/ruben/mingw-w64/prereq/x86_64-w64-mingw32/install --with-cloog=/home/ruben/mingw-w64/prereq/x86_64-w64-mingw32/install --disable-ppl-version-check --disable-cloog-version-check --enable-cloog-backend=isl --with-host-libstdcxx='-static -lstdc++ -lm' --enable-shared --enable-static --enable-threads=win32 --enable-plugins --disable-multilib --enable-languages=c,lto,c++,objc,obj-c++,fortran,java --enable-libgomp --enable-fully-dynamic-string --enable-libstdcxx-time --disable-nls --disable-werror --enable-checking=release --with-gnu-as --with-gnu-ld --disable-win32-registry --disable-rpath --disable-werror --with-libiconv-prefix=/home/ruben/mingw-w64/prereq/x86_64-w64-mingw32/install --with-pkgversion=rubenvb-4.7.2-release --with-bugurl=mingw-w64-public@lists.sourceforge.net CC= CFLAGS='-O2 -march=nocona -mtune=core2 -fomit-frame-pointer -momit-leaf-frame-pointer' LDFLAGS=
Thread model: win32
gcc version 4.7.2 (rubenvb-4.7.2-release)
```

**Comment by ABaumgaertner** [comment] 2015-03-03 23:42
if changed the build env to thread model win32 and recompiled all libraries and dependencies.
result is still the same - build with included libs fail. i've includede the --verbose output
ABaumgaertner/b945c6c940c082d5133d

anyway - if you manage to include the binaries, problems solved :-)
I think most users will happily accept a bundled version of rmagick and imagemagick

ruby 2.2.2p86 (2015-03-03 revision 49825) [x64-mingw32]

**Comment by richpeck** [comment] 2015-03-05 13:56
Off topic, but how are you able to compile the latest version of Ruby on Windows? I'm getting all sorts of dependency errors with zlib & OpenSSL!

**Comment by linduxed** [comment] 2015-03-05 15:39
To keep the issue on track, I recommend you take off topic questions to [Gitter](https://gitter.im/gemhome/rmagick) or message the individual users that regularly participate in the Windows-centric issues.

**Comment by richpeck** [comment] 2015-03-05 16:45
Sorry about that - it's fixed now anyways :)

**Comment by vassilevsky** [comment] 2015-03-06 08:10
It wasn't far off the topic though :)

**Comment by richpeck** [comment] 2015-03-06 09:55
hahaha /sarcasm :dancer:

**Comment by linduxed** [comment] 2015-03-06 13:06
I'll be deleting these last comments to clean things up a bit.

**Comment by u338steven** [comment] 2015-03-10 23:39
> \3. the included lib files are not compatible with ld

I upgraded ```ld```(```binutils```) from 2.24 to 2.25 and then I can duplicate this issue.
It might be ```ld``` issue.

If ```ld``` version is 2.25, it is necessary to downgrade it or regenerate ```CORE_RL_Magick_.lib```

Files for downgrading (for MSYS2):
http://sourceforge.net/projects/msys2/files/REPOS/MSYS2/x86_64/binutils-2.24-1-x86_64.pkg.tar.xz/download
http://sourceforge.net/projects/msys2/files/REPOS/MINGW/x86_64/mingw-w64-x86_64-binutils-2.24-9-any.pkg.tar.xz/download

Command examples:
```
pacman -U binutils-2.24-1-x86_64.pkg.tar.xz
pacman -U mingw-w64-x86_64-binutils-2.24-9-any.pkg.tar.xz
```

 --- 

Steps:
For now, we should 
1. remove ```-lX11``` from ```extconf.rb``` for mingw and mswin
2. write this knowledge in the wiki

In the future,
3. publish gems for Windows including prebuilt rmagick binaries and ImageMagick dlls

**Comment by jetamartin** [comment] 2015-05-29 17:13
Was anyone able to get this to work with Windows 8.1?  I followed the  instructions as noted in the first post but I was not successful in getting it to work...that said I'm not sure that I executed all of the suggested steps in the initial post correctly as they were fairly succinct and I'm not a windows expert. 
eg.."gendef CORE_RL_magick_.dll"

Are there any specific plans to allow ImageMagick/rMagick to work on Windows platforms???? if not I guess I'll just have to look for an alternative solution.

**Comment by vassilevsky** [comment] 2015-05-29 19:22
This project is run by volunteers and we just release whatever someone contributes :) No strategic plans or anything like that :)

We realize that Windows support is important. Hopefully we make it so that a Windows version of the gem is released alongside the Linux one.

**Comment by u338steven** [comment] 2015-05-29 19:42
@jetamartin 
FWIW, simple installation guide(workaround):
[Installing on Windows · gemhome/rmagick Wiki](https://github.com/gemhome/rmagick/wiki/Installing-on-Windows)

**Comment by jetamartin** [comment] 2015-05-29 19:49
Ilya,  thanks for the quick reply. I totally understand. If I could help I would but I don't have the Windows expertise that would be needed to help.  

I was hoping that by following the initial steps noted by ABaumgaertner  that I could get it to work on Windows 8.1. At this point I'm not sure if I did something wrong following the steps noted by Abaumgaertner or if it just doesn't work on Windows 8.1. Do you know his steps work on Windows 8.1?
There were a number of responses back and forth regarding Abaumgaertner's initial recommendations. Based on that dialogue I wasn't able to determine if there are extra steps that need to be accounted for to make this work properly. 

Any timeline/target timeframe for Linux/Windows support?

**Comment by jetamartin** [comment] 2015-05-29 19:51
u338steven,  thanks for your reply. Do you happen to know if anyone has been successful in using the workaround on Windows 8.1?  If I have questions regarding the workaround steps is there someone who might respond to my questions?
Thanks.

**Comment by u338steven** [comment] 2015-05-29 20:36
I confirmed the workaround with:
- Windows 7 x64 & 8.1 x64
- ruby 2.2.2p95 (2015-04-13 revision 50295) [x64-mingw32]
- ImageMagick-6.9.1-Q16

> If I have questions regarding the workaround steps is there someone who might respond to my questions?

I will do as much as I can.

**Comment by jetamartin** [comment] 2015-05-29 21:16
u338steven, 
I followed the steps noted in the workaround (with some minor mods...to match my installation..e.g.,location of ImageMagick) you referenced (https://github.com/rmagick/rmagick/wiki/Installing-on-Windows) and I was able to install rMagick successfully. I haven't tried installing ImageMagick Gem yet. 
--> I assume that is a separate step?  
But hopefully that will work. If it does I'll post the results.

One difference I noted on my system is that I have both Ruby 1.9.3 and Ruby 2.1.0 installed on my system...and there was no C:\RailsInstaller\Ruby1.9.3\setup_environment.bat file on my system. However the file did exist under 2.1.0 directory (C:\RailsInstaller\Ruby2.1.0). 
--> Perhaps the .bat file only exist on the most current version of Ruby that you have installed? (Note: I used RailsInstaller when I setup my Windows environment).  

Cheers,
Jet

**Comment by u338steven** [comment] 2015-05-29 22:39
> I haven't tried installing ImageMagick Gem yet. 
> --> I assume that is a separate step?

If you have already installed ImageMagick, you can skip that step.

> --> Perhaps the .bat file only exist on the most current version of Ruby that you have installed? (Note: I used RailsInstaller when I setup my Windows environment).

Sorry, it is a RailsInstaller issue, not RMagick.
I have no idea about it because I have never installed multiple versions of RailsInstaller.

**Comment by jetamartin** [comment] 2015-05-30 00:48
Steven,

Thanks for the response. 
Just to clarify I only have one RailsInstaller on my system but I have multiple versions of Ruby installed 1.9.3 and 2.1.0. I assumed that RailsInstaller only produces the .bat file for the most recent version of Ruby.
Cheers.

**Comment by jmthomas** [comment] 2015-07-09 21:22
Windows 7 SP 1 x64
Ruby 2.1.6p336
DevKit 64 installed
Installed ImageMagick to C:\Program Files\ImageMagick-6.9.1-Q16
Error was "Unable to get ImageMagick version"

Looks like line 123 in extconf.rb is trying to get the version:
````
`convert -version` =~ /Version: ImageMagick (\d+\.\d+\.\d+)-\d+ /
````
However when I type convert -version I get this:
````
C:\Users\JMTHOMAS>convert -version
Version: ImageMagick 6.9.1--7 Q16 x64 2015-07-04 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2015 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP
Delegates (built-in): bzlib cairo freetype jng jp2 jpeg lcms lqr openexr pangocairo png ps rsvg tiff
 webp xml zlib
````
Thus the regex is incorrect. There is an extra '-' between the version number and the 7. I think if you remove the back end of that regex (-\d+) it will work.

**Comment by mockdeep** [comment] 2019-03-09 17:43
Going to close this issue for now. If anybody runs into additional issues installing on Windows, please open a new issue.

**Closed by mockdeep** 2019-03-09 17:43 UTC
Labels: Windows
