### ISSUE TITLE
Support for ImageMagic >= 7

### ISSUE THREAD

**Issue by darix** [rmagick/rmagick#271] opened 2017-07-20 13:42 UTC
rmagick.h:1210:51: error: unknown type name ‘MagickPixelPacket’; did you mean ‘PixelPacket’?

any plans for supporting this?

**Comment by alexandru-calinoiu** [comment] 2017-08-02 14:33
Duplicate of https://github.com/rmagick/rmagick/issues/265

**Comment by mockdeep** [comment] 2019-03-09 17:00
duplicate of #256.

**Closed by mockdeep** 2019-03-09 17:00 UTC
Labels: ImageMagick 7

**Comment by Nakilon** [comment] 2020-07-25 05:47
The #256 says I should `brew upgrade` but it does not help.

**Comment by mockdeep** [comment] 2020-07-25 17:05
@Nakilon can you give some more specifics about the error that you're seeing? You'll also need to uninstall and reinstall rmagick in order to get it to compile against your ImageMagick version:

```rb
gem uninstall rmagick
gem install rmagick # or run `bundle` if you have it in your `Gemfile`
```

**Comment by Nakilon** [comment] 2020-07-25 18:18
@mockdeep I'm sorry for false alert. I had multiple gems installed at different time and after I prepended `bundle exec` the issue has gone.
