### ISSUE TITLE
in place unsharp_mask

### ISSUE THREAD

**Issue by bf4** [rmagick/rmagick#32] opened 2014-07-24 14:05 UTC
<a href="https://github.com/mmb"><img src="https://avatars.githubusercontent.com/u/24275?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [mmb](https://github.com/mmb)**
_Tuesday Apr 03, 2012 at 00:46 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/51_

---

Why isn't there an unsharp_mask!

To do it in place, is this the usual way:

``` ruby
img = img.unsharp_mask
```

**Comment by Watson1978** [comment] 2024-04-25 09:13
Basically, I think the problem is related to memory usage, and I think it should be resolved by https://github.com/rmagick/rmagick/pull/836 

If we support this issue, we need to be considered about other methods....
That would not be supported as we would require a lot of work.

**Closed by Watson1978** 2024-04-25 09:13 UTC
