### ISSUE TITLE
Windows, MSYS2/MinGW - building with 7.0.9

### ISSUE THREAD

**Issue by MSP-Greg** [rmagick/rmagick#1047] opened 2020-02-14 23:49 UTC
After a little hacking of extconf.rb, compiling got all the way to:
```
linking shared-object RMagick2.so
... /x86_64-w64-mingw32/bin/ld.exe: rmmain.o:rmmain.c:(.text+0xef):
undefined reference to `_aligned_msize'
```

I'm not much of a c type, but I asuume that being able to build with the MSYS2/MinGW package would be helpful.  But, I'm not really familiar with ImageMagick...

Happy to try anything locally...

**Comment by Watson1978** [comment] 2020-02-15 00:14
Can you tell me more information of procedure to reproduce?

**Comment by MSP-Greg** [comment] 2020-02-15 00:20
Of course.  Allow me to ask a few dumb questions...

1. Can/do you run windows locally?

2. Ruby installed >= 2.4?

3. Do you have MSYS2 installed?

If you're not running Windows, it would take me a little while, but I could set up a branch to run it on Actions.

**Comment by Watson1978** [comment] 2020-02-15 00:42
I've been using Windows via virtual machine.
I'm using [RubyInstaller for Windows](https://rubyinstaller.org) and I think it contains MSYS2.

**Comment by MSP-Greg** [comment] 2020-02-15 00:50
If you have Ruby >= 2.4 and you have a `msys64` folder at the same level as the Ruby bin folder, you've got the framework.

If so, give me a second to check what pacman commands you need to run to update things to compile with.

**Comment by Watson1978** [comment] 2020-02-15 00:52
Thanks. I'll try that :)

**Comment by MSP-Greg** [comment] 2020-02-15 01:44
Sorry, AFK for a bit there.  But I did recall that it would be best if you have the most reent release of whatever version of Ruby you want to use, hence, 2.4.9, 2.5.7, 2.6.5, or 2.7.0

We'll need to update the MSYS2 install and install the imagemagick package, then you'll need to add my hacked extconf.rb file.  The update may take a few minutes, depends on you download speed, etc...

Do you have preferred shell in Windows, cmd or powershell?

**Comment by Watson1978** [comment] 2020-02-15 01:56
I'm not familiar with Windows.
So I don't know about commonly used shells, but I'm using `cmd`.

**Comment by MSP-Greg** [comment] 2020-02-15 02:07
Try typing
```
ridk version
```
you should see:
```
msys2:
  path: <path for your system>
```
Take \<path for your system\> and type:
```
set PATH=<path for your system>\mingw64\bin;<path for your system>\usr\bin;%PATH%
```
then the following should show the pacman version as a check to see if we're ok.
```
pacman --version
```

**Comment by MSP-Greg** [comment] 2020-02-15 02:22
First, if a message in the console says something like 'close your terminal/console/window', do so and repeat the below command when you open another cmd window:
```
set PATH=<path for your system>\mingw64\bin;<path for your system>\usr\bin;%PATH%
```

Ok, now we'll update your build tools and get the imagemagick package installed.

First, type the following
```
pacman.exe -Syyuu --noconfirm
```
you may see a 'close window' message, if so close the window and reopen as mentioned at the top of this message.

Then repeat that just for a check, you should see something like:
```
:: Starting core system upgrade...
 there is nothing to do
:: Starting full system upgrade...
 there is nothing to do
```

Once you see that, type the following to update your build tools (gcc, pkg-config, etc):
```
pacman.exe -S --noconfirm --needed --noprogressbar mingw-w64-x86_64-toolchain
```

then, finally, install imagemagick:
```
pacman.exe -S --noconfirm --needed --noprogressbar mingw-w64-x86_64-imagemagick 
```

Once that's done, you're ready to run:
```
rake -rdevkit compile
```

Attached is the hacked extconf.rb file I used, renamed with a txt extension, as GitHub won't allow *.rb files to be attached.  Note that it is really a hack, and needs more conditional code for OS/platform checks.  I just wanted to get to the point where compile started...


[extconf.rb.txt](https://github.com/rmagick/rmagick/files/4207645/extconf.rb.txt)

**Comment by MSP-Greg** [comment] 2020-02-15 02:27
Apologies.  I just thought about how you may need git, maybe the GitHub windows client, and obviously this repo to run `rake compile`.   Let me know if you want help with that...  I assume you're on macOS, and I haven't seriously worked on macOS for a few years...

**Comment by MSP-Greg** [comment] 2020-02-15 02:36
And apologies #2.  Been coding for about 50 years, and using Windows since DOS days.  It's easy to assume things  I assumed `ruby -v` shows what it should.  If it doesn't let me know...

**Comment by Watson1978** [comment] 2020-02-15 04:41
Added workaround into master branch. Can you try it ?

**Comment by MSP-Greg** [comment] 2020-02-15 05:42
> With this procedure, ImageMagick seems to be unstable with my environment

Yes, something is not right.  Specs didn't go well.

With master as is, it doesn't compile on my system.  Using the extconf.rb I hacked, it does.

I've attached three files with logs of each.

[compile_bad.txt](https://github.com/rmagick/rmagick/files/4207789/compile_bad.txt)
[compile_good.txt](https://github.com/rmagick/rmagick/files/4207790/compile_good.txt)
[spec_results.txt](https://github.com/rmagick/rmagick/files/4207788/spec_results.txt)

The build folder in MSYS2 is here:
https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-imagemagick

The main build file is [PKGBUILD](https://github.com/msys2/MINGW-packages/blob/master/mingw-w64-imagemagick/PKGBUILD).

I'm not that familiar with imagemagick, so I may not be much help, but happy to test anything.

Also, I'm -0600, so I'm probably AFK for the night.  Thanks for the quick fix for this.

It would certainly be nice if the MSYS2 package worked, as standard Windows Ruby builds allow gemspec metadata that would install the package automatically when the gem is installed.

Most of the MSYS2 packages I've worked with are standard packages needed for Ruby or database connectors.  I'm surprised the package tested so poorly, as obviously other packages work fine (PR https://github.com/rmagick/rmagick/pull/1042)...

**Comment by mockdeep** [comment] 2020-09-26 03:09
@Watson1978 @MSP-Greg are there next actions we need to take to close this issue out?

**Comment by Watson1978** [comment] 2020-09-26 03:27
I will close this because building issue on MSYS with IM7 has been fixed.
Feel free to reopen if you need something.

**Closed by Watson1978** 2020-09-26 03:27 UTC
Labels: ImageMagick 7
