### ISSUE TITLE
PDF's first page is not cropping. Always saving black image.

### ISSUE THREAD

**Issue by KiranAdroit** [rmagick/rmagick#289] opened 2018-01-11 06:30 UTC
Hello,
I am using Rmagick with carrierwave to crop and upload image. When I crop first page of pdf then it is saving image but it is totally black. The portion that I have selected from pdf is not reflecting. Following is the code that I am using to crop the pdf's first page.
`
manipulate! do |img,index|

                 if index.zero?    
                    x = model.pdf_x.to_i
                    y = model.pdf_y.to_i
                    w = model.pdf_w.to_i
                    h = model.pdf_h.to_i
                    img.crop!(x, y, w, h)                    
                end    
end
`
Any example or tutorial to crop first page of pdf?

**Comment by Watson1978** [comment] 2024-04-25 22:21
I'm guessing this is related to https://github.com/rmagick/rmagick/issues/270
Unfortunately, I can't reproduce this problem...

I don't know if it comes from the PDF content or the old ImageMagick or ghostscript.

So, I will close this.
Feel free to reopen if you have still any problem.

**Closed by Watson1978** 2024-04-25 22:21 UTC
Labels: bug
