### ISSUE TITLE
expected Magick::GravityType, got String

### ISSUE THREAD

**Issue by prativapokhrel** [rmagick/rmagick#700] opened 2019-05-22 10:14 UTC
I am using rmagick(2.16.0) and mini_magick(4.9.3) with ImageMagick(8.9) and I am getting this TypeError while running a test which uses an image from assets.

 TypeError:
       wrong enumeration type - expected Magick::GravityType, got String
# /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/processing/rmagick.rb:238:in `composite!'
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/processing/rmagick.rb:238:in `block in resize_and_pad'
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/processing/rmagick.rb:356:in `block in manipulate!'
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/processing/rmagick.rb:355:in `each'
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/processing/rmagick.rb:355:in `each_with_index'
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/processing/rmagick.rb:355:in `manipulate!'
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/processing/rmagick.rb:229:in `resize_and_pad'
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/uploader/processing.rb:83:in `block (2 levels) in process!'
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/uploader/processing.rb:75:in `each'
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/uploader/processing.rb:75:in `block in process!'
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/uploader/callbacks.rb:15:in `with_callbacks'
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/uploader/processing.rb:74:in `process!'
     # /usr/local/bundle/bundler/gems/carrierwave_backgrounder-460394b0e2c0/lib/backgrounder/delay.rb:14:in `process!'
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/uploader/callbacks.rb:14:in `block in with_callbacks'
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/uploader/callbacks.rb:14:in `each'
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/uploader/callbacks.rb:14:in `with_callbacks'
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/uploader/cache.rb:139:in `cache!'
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/uploader/versions.rb:312:in `block in cache_versions!'
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/uploader/versions.rb:310:in `each'
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/uploader/versions.rb:310:in `cache_versions!'
     # /usr/local/bundle/bundler/gems/carrierwave_backgrounder-460394b0e2c0/lib/backgrounder/delay.rb:6:in `cache_versions!'
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/uploader/callbacks.rb:16:in `block in with_callbacks'
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/uploader/callbacks.rb:16:in `each'
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/uploader/callbacks.rb:16:in `with_callbacks'
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/uploader/cache.rb:139:in `cache!'
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/mounter.rb:44:in `block in cache'
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/mounter.rb:42:in `map'
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/mounter.rb:42:in `cache'
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/mount.rb:146:in `company_logo='
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/mount.rb:367:in `company_logo='
     # /usr/local/bundle/bundler/gems/carrierwave-3f540b97fe84/lib/carrierwave/orm/activerecord.rb:75:in `company_logo='
     # /usr/local/bundle/gems/machinist-2.0/lib/machinist/lathe.rb:56:in `assign_attribute'
     # /usr/local/bundle/gems/machinist-2.0/lib/machinist/lathe.rb:29:in `method_missing'
     # ./spec/support/blueprints.rb:329:in `block in <top (required)>'
     # /usr/local/bundle/gems/machinist-2.0/lib/machinist/blueprint.rb:26:in `instance_eval'
     # /usr/local/bundle/gems/machinist-2.0/lib/machinist/blueprint.rb:26:in `make'
     # /usr/local/bundle/gems/machinist-2.0/lib/machinist/active_record/blueprint.rb:6:in `make!'
     # /usr/local/bundle/gems/machinist-2.0/lib/machinist/machinable.rb:52:in `block in make!'
     # /usr/local/bundle/gems/machinist-2.0/lib/machinist/machinable.rb:88:in `decode_args_to_make'
     # /usr/local/bundle/gems/machinist-2.0/lib/machinist/machinable.rb:50:in `make!'
     # ./spec/features/v4/guest/jobs/show_spec.rb:7:in `block (2 levels) in <top (required)>'
     # /usr/local/bundle/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:123:in `block in run'
     # /usr/local/bundle/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `loop'
     # /usr/local/bundle/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `run'
     # /usr/local/bundle/gems/rspec-retry-0.6.1/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
     # /usr/local/bundle/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:37:in `block (2 levels) in setup'

**Comment by Watson1978** [comment] 2019-05-22 10:21
Could you please provide the reproduce code ?

**Comment by mockdeep** [comment] 2019-05-22 17:46
Hi @prativapokhrel, it looks like you might be calling `resize_and_pad` with the 4th argument being a string. However, it should be a [`Magick::GravityType`](https://rmagick.github.io/constants.html#GravityType). If you leave off the 4th argument it defaults to `Magick::CenterGravity`. If this doesn't fix your issue, please provide a code sample that demonstrates the issue you're seeing.

**Comment by mockdeep** [comment] 2019-06-01 07:17
Closing for now. If you are still having the issue, please provide some more context and we can reopen it.

**Closed by mockdeep** 2019-06-01 07:17 UTC
Labels: more-information-needed
